apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-backend
  template:
    metadata:
      labels:
        app: spring-boot-backend
    spec:
      containers:
      - name: spring-boot-backend
        image: bunny1269/bootcamp-backend:latest
        env:
        - name: MQTT_HOST
          value: mqtt-tcp
        ports:
        - containerPort: 8080
          name: apiport
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-backend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: spring-boot-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        image: bunny1269/bootcamp-mqtt:latest
        ports:
        - containerPort: 1883
          name: mqtttcp
        - containerPort: 8083
          name: mqttws
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-tcp
spec:
  ports:
  - port: 1883
    name: mqtttcp
  selector:
    app: mqtt
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  type: LoadBalancer
  ports:
  - port: 8083
  selector:
    app: mqtt
      